//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNetProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int id { get; set; }
        public Nullable<System.DateTime> upload_date { get; set; }
        public string text { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_picture { get; set; }
    
        public virtual Pictures Pictures { get; set; }
        public virtual Users Users { get; set; }
    }
}
