//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNetProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Picture()
        {
            this.Albums = new HashSet<Album>();
        }
    
        public int id { get; set; }
        public byte[] img { get; set; }
        public System.DateTime upload_date { get; set; }
        public string descr { get; set; }
        public Nullable<int> id_comment { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> rating { get; set; }
        public string title { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Album> Albums { get; set; }
    }
}
