//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNetProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PicturesAlbums
    {
        public int id { get; set; }
        public int album_id { get; set; }
        public int pictures_id { get; set; }
    
        public virtual Albums Albums { get; set; }
        public virtual Pictures Pictures { get; set; }
    }
}
